feat: random hadith feature added
Xayrulloh/ReminderBot pull request #132
Opened 2023-11-18 10:49 UTC by Xayrulloh

2023-11-18 12:25 UTC, toshmukhamedov requested changes

2023-11-18 12:25 UTC, toshmukhamedov commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
`hadith[0]` bo’lmay qolishi mumkin bo’lgan holatni oldini olish kerak. Misol uchun `Hozircha hadis mavjud emas` shunga o'xshash

2023-11-18 12:25 UTC, toshmukhamedov commented on scenes/hadith.ts
>  scene.step(async (ctx) => {
Bizda userdan ketma-ket bir nechta ma’lumotlar kiritishi talab qilinmaydi. Shunga ko’ra shunchaki command orqali handle qilish kerak

2023-11-18 12:49 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
hadis[0] har doim bo'ladi

2023-11-18 12:50 UTC, Xayrulloh commented on scenes/hadith.ts
>  scene.step(async (ctx) => {
buni atiydan keyincali yana ubu nimadir qo'wiw kere bo'sa dib

2023-11-18 12:50 UTC, toshmukhamedov commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
kim garantiyalaydi

2023-11-18 12:51 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
man, db da data bo'sa bo'ldi, hozirgi vaziyatda bo'sa data bor ya'ni hadislar

2023-11-18 12:51 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
buyoda luboy 1tasini oberdganmanku, wuni olarkande lekn u array icida bo'larkan, wunicun [0] qiganman

2023-11-18 12:52 UTC, toshmukhamedov commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
misol uchun manda localda u collectionni o’zi yo’q shu holatda bo’sh string kelishi noto’g’ri manimcha

2023-11-18 12:52 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
local ☠️

2023-11-18 12:52 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
da man faqat prodni o'ylaganman)

2023-11-18 12:53 UTC, toshmukhamedov commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
ok prod db o’chib ketdi deb tasavvur qiling

2023-11-18 12:53 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
okay, hozi fix qilamis

2023-11-18 12:55 UTC, Xayrulloh commented on scenes/hadith.ts
> +  hadith = '\n\n<pre>' + hadith[0]?.content + '</pre>'
![image](https://github.com/Xayrulloh/ReminderBot/assets/91729108/569ecc34-7c5c-4e25-b74a-9f566332118a)

qale

2023-11-18 12:59 UTC, toshmukhamedov submitted a review, later dismissed

2023-11-18 14:49 UTC, eugene0928 submitted a review, later dismissed

2023-11-19 07:26 UTC, toshmukhamedov approved these changes

2023-11-19 13:19 UTC, merged