feat: juma image sending
Xayrulloh/ReminderBot pull request #133
Opened 2023-11-19 14:56 UTC by eugene0928

2023-11-19 15:00 UTC, Xayrulloh requested changes

2023-11-19 16:27 UTC, Xayrulloh submitted a review, later dismissed

2023-11-19 16:35 UTC, toshmukhamedov requested changes

2023-11-19 16:35 UTC, toshmukhamedov commented on cron/cron.ts
> +        if(weekDay != 5) {
ko’pincha holatda positivega tekshirish tavsiya etiladi huddi boolean qiymat saqlovchi o’zgaruvchi nomi kabi.
Good: 
```js
const isVisible = true;
const isEnabled = false;
```
Bad: 
```js
const isHide = false;
const isDisabled = true;
```

Bu ne v temadek tuyulishi mumkin. Aytmoqchimanki `weekday` `5` ekanligiga tekshirgan yaxshi

2023-11-20 05:02 UTC, Xayrulloh approved these changes

2023-11-20 05:03 UTC, toshmukhamedov approved these changes

2023-11-20 05:03 UTC, merged