refactor: unused translations removed; notification message changed; …
Xayrulloh/ReminderBot pull request #137
Opened 2023-11-25 10:03 UTC by Xayrulloh

…notification scene logic and view changed

2023-11-25 10:16 UTC, toshmukhamedov requested changes

2023-11-25 10:16 UTC, toshmukhamedov commented on translate/uz.json
>    "notificationMessage": "Har namoz vaqti bo'lganda ogohlantirilishga rozimisiz?",
```suggestion
```

2023-11-25 10:16 UTC, toshmukhamedov commented on scenes/notification.ts
> -  const message = HLanguage('notificationMessage')
Buni `/start` commanddan olib tashlash kerak

2023-11-25 10:31 UTC, Xayrulloh commented on translate/uz.json
>    "notificationMessage": "Har namoz vaqti bo'lganda ogohlantirilishga rozimisiz?",
nma o'zgardi

2023-11-25 10:31 UTC, Xayrulloh commented on translate/uz.json
>    "notificationMessage": "Har namoz vaqti bo'lganda ogohlantirilishga rozimisiz?",
bo'ldi cundim

2023-11-25 10:32 UTC, Xayrulloh commented on translate/uz.json
>    "notificationMessage": "Har namoz vaqti bo'lganda ogohlantirilishga rozimisiz?",
qogan joylada iwlatilinganku

2023-11-25 10:32 UTC, Xayrulloh commented on scenes/notification.ts
> -  const message = HLanguage('notificationMessage')
why

2023-11-25 10:40 UTC, eugene0928 commented on translate/uz.json
> +  "setPrayerTimes": "Xabarnoma kelishini hohlagan vaqtlaringizni belgilang va saqlang",
olgingisi yaxshiro edi shekilli

2023-11-25 10:45 UTC, toshmukhamedov commented on scenes/notification.ts
> -  const message = HLanguage('notificationMessage')
boshida rozimasman bossam keyin `notification`ni `true` qilolmimanku baribir

2023-11-25 10:45 UTC, toshmukhamedov commented on translate/uz.json
>    "notificationMessage": "Har namoz vaqti bo'lganda ogohlantirilishga rozimisiz?",
ishlatilgan joydan ham copish kere

2023-11-26 07:11 UTC, toshmukhamedov requested changes

2023-11-26 07:11 UTC, toshmukhamedov commented on translate/uz.json
>    "agreementNotification": ["Roziman", "Rozimasman"],
```suggestion
```
unused

2023-11-26 07:20 UTC, Xayrulloh commented on translate/uz.json
> +  "setPrayerTimes": "Xabarnoma kelishini hohlagan vaqtlaringizni belgilang va saqlang",
Optimizatsya qildk

2023-11-26 07:24 UTC, toshmukhamedov commented on translate/uz.json
> +  "setPrayerTimes": "Xabarnoma kelishini hohlagan vaqtlaringizni belgilang va saqlang",
ha 16 ta belgili so’z o’rniga 12 ta belgili so’z qo’llanildi 😂

2023-11-26 07:26 UTC, Xayrulloh commented on translate/uz.json
> +  "setPrayerTimes": "Xabarnoma kelishini hohlagan vaqtlaringizni belgilang va saqlang",
Erinmi sanab ciqdismi)

Quyow dgan vaqt ham boridi wunicun namoz vaqtlari diw notori bolarkan

2023-11-26 07:26 UTC, toshmukhamedov commented on translate/uz.json
> +  "setPrayerTimes": "Xabarnoma kelishini hohlagan vaqtlaringizni belgilang va saqlang",
![image](https://github.com/Xayrulloh/ReminderBot/assets/79999469/708c0cd6-f9f4-4915-9aaa-a03267557f7d)
@eugene0928 Quyosh chiqishi namoz vaqti emasligini hisobga olib o'zgartirildi

2023-11-26 15:15 UTC, eugene0928 approved these changes

2023-11-26 15:22 UTC, toshmukhamedov approved these changes

2023-11-26 15:22 UTC, merged