refactor/packages
Xayrulloh/ReminderBot pull request #87
Opened 2023-09-24 17:24 UTC by atoshmukhamedov

2023-09-24 17:57 UTC, Xayrulloh requested changes

2023-09-24 17:57 UTC, Xayrulloh commented on scenes/advertise.ts
> +scene.wait('hadith').on('message:text', async (ctx) => {
What does hadith

2023-09-24 17:57 UTC, Xayrulloh commented on scenes/donate.ts
> +scene.wait('amount').on('message:text', async (ctx) => {
Same

2023-09-24 17:57 UTC, Xayrulloh commented on scenes/fasting.ts
> +scene.wait('fasting').on('callback_query:data', async (ctx) => {
Same

2023-09-24 17:57 UTC, Xayrulloh commented on scenes/hadith.ts
> +  await ctx.reply('The hadith is written, thank you. You are doing your best :)')
Emotional damage

2023-09-24 17:57 UTC, Xayrulloh commented on scenes/language.ts
> +  await ctx.deleteMessage()
Where it came from

2023-09-24 17:58 UTC, Xayrulloh commented on scenes/language.ts
> +  await ctx.deleteMessage()
Esladm

2023-09-25 03:15 UTC, atoshmukhamedov commented on scenes/language.ts
> +  await ctx.deleteMessage()
man prosto await qo'shganman

2023-09-25 03:15 UTC, atoshmukhamedov commented on scenes/hadith.ts
> +  await ctx.reply('The hadith is written, thank you. You are doing your best :)')
?

2023-09-25 03:16 UTC, atoshmukhamedov commented on scenes/advertise.ts
> +scene.wait('hadith').on('message:text', async (ctx) => {
endi wait argument qabul qilar ekan

2023-09-25 03:16 UTC, Xayrulloh commented on scenes/hadith.ts
> +  await ctx.reply('The hadith is written, thank you. You are doing your best :)')
Hadith wrote => hadith written

2023-09-25 03:17 UTC, Xayrulloh commented on scenes/advertise.ts
> +scene.wait('hadith').on('message:text', async (ctx) => {
Nma qiladi uni

2023-09-25 03:19 UTC, atoshmukhamedov commented on scenes/advertise.ts
> +scene.wait('hadith').on('message:text', async (ctx) => {
<img width="870" alt="Screenshot 2023-09-25 at 08 18 26" src="https://github.com/Xayrulloh/ReminderBot/assets/79999469/ec76a78a-917a-467e-b70a-7b9f7126fa13">

2023-09-25 03:21 UTC, atoshmukhamedov commented on scenes/advertise.ts
> +scene.wait('hadith').on('message:text', async (ctx) => {
umuman oganda farqi yo'q unga unique bo'sa bo'ldi. Meaningful bo'lishi uchun nimani kutvotganizi yozasiz.

2023-09-25 03:21 UTC, atoshmukhamedov commented on scenes/hadith.ts
> +  await ctx.reply('The hadith is written, thank you. You are doing your best :)')
what is wrong?

2023-09-25 03:32 UTC, Xayrulloh commented on scenes/hadith.ts
> +  await ctx.reply('The hadith is written, thank you. You are doing your best :)')
Nothing, never mind

2023-09-25 03:33 UTC, merged